In [1]:
from torch import tensor, zeros, float32, zeros_like, stack, tril, ones
from torch.nn.functional import softmax

In [13]:
# Karpathy's self-attention trick
batch_size, window_size, embedding_dim = 2, 3, 2
x_row = tensor([[1, 10], [3, 30], [5, 50]], dtype=float32)
x = stack([x_row, x_row*10])
print("X = ")
print(x)
print()

X = 
tensor([[[  1.,  10.],
         [  3.,  30.],
         [  5.,  50.]],

        [[ 10., 100.],
         [ 30., 300.],
         [ 50., 500.]]])



In [11]:
# Question: How to get averages of the window up to the present.
# [ a b c d ] => [ a ab abc abcd ]

# The manual way
result = zeros_like(x)
for i in range(x_row.shape[1]):
    result[:, i:i+1, :] = x[:, :i+1].mean(1, keepdim=True)
print("manual result = ")
print(result)
print()

manual result = 
tensor([[[  1.,  10.],
         [  2.,  20.],
         [  0.,   0.]],

        [[ 10., 100.],
         [ 20., 200.],
         [  0.,   0.]]])



In [10]:
# Neutral weights
weights = zeros(window_size, window_size)

# Masking future
mask = tril(ones(window_size, window_size))
att = weights.masked_fill(mask == 0, float("-inf"))

# Windowing with logit weights
y = softmax(att, dim=-1) @ x
print(y)

tensor([[[  1.0000,  10.0000],
         [  2.0000,  20.0000],
         [  3.0000,  30.0000]],

        [[ 10.0000, 100.0000],
         [ 20.0000, 200.0000],
         [ 30.0000, 300.0000]]])


In [14]:
from karpathy_series.gpt_from_scratch.util import masked_window
y = masked_window(weights) @ x
print(y)

tensor([[[  1.0000,  10.0000],
         [  2.0000,  20.0000],
         [  3.0000,  30.0000]],

        [[ 10.0000, 100.0000],
         [ 20.0000, 200.0000],
         [ 30.0000, 300.0000]]])
